[alias]
bb = "run --release --bin burnbench --"
xtask = "run --target-dir target/xtask --color always --package xtask --bin xtask --"

[env]
# Libtorch paths (deps add /lib and /include so we don't need to add them)
LIBTORCH = "C:\\Users\\elect\\anaconda3\\Lib\\site-packages\\torch" 
LIBTORCH_LIB = "C:\\Users\\elect\\anaconda3\\Lib\\site-packages\\torch" 
LIBTORCH_INCLUDE = "C:\\Users\\elect\\anaconda3\\Lib\\site-packages\\torch"

# CUDA paths and environment variables
TORCH_CUDA_VERSION = "cu121"  
CUDA_PATH = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1"

# Libuv path
LIBUV = " C:\\Users\\elect\\anaconda3\\pkgs\\libuv-1.49.2-h2466b09_0\\Library\\bin"

# Other paths
LIB1 = "C:\\Users\\elect\\anaconda3\\Lib\\site-packages\\torch\\lib" 
LIB2 = "C:\\Users\\elect\\anaconda3\\Lib\\site-packages\\torch\\bin" 
LIB3 = "C:\\Users\\elect\\anaconda3\\pkgs\\intel-openmp-2023.1.0-h59b6b97_46320\\Library\\bin" 

# Path
PATH = "{PATH};{LIBTORCH};{LIBTORCH_LIB};{LIBTORCH_INCLUDE};{CUDA_PATH};{LIBUV};{LIB1};{LIB2};{LIB3}"